'use client'

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useAgentStore } from '@/stores/agentStore'
import { useMessageStore } from '@/stores/messageStore'
import { MemoryRecord, MessageRecord, AgentRecord, AgentRelationship } from '@/types/database'
import { ArrowLeft, Send, User, MessageCircle, Brain, TrendingUp, Heart, Clock, Palette, Moon, BookOpen, Swords, Network, Library, GraduationCap, Users, Languages, Sparkles } from 'lucide-react'
import { PlaygroundLogo } from '@/components/PlaygroundLogo'
import { motion } from 'framer-motion'
import { GradientOrb } from '@/components/ui/animated-background'
import { MetaLearningState, SkillProgression } from '@/types/metaLearning'

// Phase 1 Components
import { EmotionRadar, EmotionBars } from '@/components/emotions/EmotionRadar'
import { EmotionTimeline } from '@/components/emotions/EmotionTimeline'
import { TimelineExplorer } from '@/components/timeline/TimelineExplorer'

// Phase 2 Components
import { CreativePortfolio } from '@/components/creative/CreativePortfolio'
import { DreamJournal } from '@/components/dreams/DreamJournal'
import { JournalViewer } from '@/components/journal/JournalViewer'
import { ProfileViewer } from '@/components/profile/ProfileViewer'
import { MemoryConsole } from '@/components/memory/MemoryConsole'
import { ChallengeHub } from '@/components/challenges/ChallengeHub'
import { RelationshipGraph } from '@/components/relationships/RelationshipGraph'
import { RelationshipCard } from '@/components/relationships/RelationshipCard'
import { MetaLearningDashboard } from '@/components/learning/MetaLearningDashboard'

import { ParallelRealityExplorer } from '@/components/parallel/ParallelRealityExplorer'
import { VoiceConsole } from '@/components/chat/VoiceConsole'

// Phase 3 Components
import { KnowledgeGraph } from '@/components/knowledge/KnowledgeGraph'
import { SharedKnowledgeLibrary } from '@/components/knowledge/SharedKnowledgeLibrary'
import { MentorshipHub } from '@/components/mentorship/MentorshipHub'
import { CollectiveIntelligencePanel } from '@/components/collective/CollectiveIntelligencePanel'
import { ConflictResolutionPanel } from '@/components/relationships/ConflictResolutionPanel'
import { NeuralActivityView } from '@/components/neural/NeuralActivityView'
import { LLMProviderToggle } from '@/components/llm/LLMProviderToggle'
import { getClientModelForProvider, LLM_PROVIDER_LABELS } from '@/lib/llm/clientPreference'
import { useLLMPreferenceStore } from '@/stores/llmPreferenceStore'

// Phase 1 Services
import { agentStatsService } from '@/lib/services/agentStatsService'
import { emotionalService } from '@/lib/services/emotionalService'
import { timelineService } from '@/lib/services/timelineService'

import { parallelRealityService, ParallelRealityExtended } from '@/lib/services/parallelRealityService'

type TabType =
  | 'chat'
  | 'memory'
  | 'emotions'
  | 'neural'
  | 'timeline'
  | 'relationships'
  | 'learning'
  | 'scenarios'
  | 'creative'
  | 'dreams'
  | 'journal'
  | 'profile'
  | 'challenges'
  | 'knowledge-graph'
  | 'knowledge-library'
  | 'collective'
  | 'mentorship'

interface RelationshipApiStats {
  totalRelationships: number
  strongBonds: number
  averageTrust: number
  averageRespect: number
  averageAffection: number
  brokenBonds: number
  mostConnectedAgent: string | null
}

function formatEmotionLabel(emotion: string | null | undefined): string {
  if (!emotion) {
    return 'Dormant'
  }

  return emotion.charAt(0).toUpperCase() + emotion.slice(1)
}

const TAB_CONFIG = [
  { id: 'chat', icon: MessageCircle, label: 'Chat', description: 'Direct conversations and model responses.' },
  { id: 'emotions', icon: Heart, label: 'Emotions', description: 'Current emotional signals and recent shifts.' },
  { id: 'neural', icon: Brain, label: 'Neural', description: 'Live thought flow, attention, and emotional activity.' },
  { id: 'timeline', icon: Clock, label: 'Timeline', description: 'A chronological view of important events.' },
  { id: 'memory', icon: Brain, label: 'Memory', description: 'Stored memories, trait evolution, and retention stats.' },
  { id: 'relationships', icon: Users, label: 'Relationships', description: 'Trust, bonds, and long-term social state.' },
  { id: 'learning', icon: TrendingUp, label: 'Learning', description: 'Patterns, recommendations, and meta-learning signals.' },

  { id: 'scenarios', icon: Sparkles, label: 'Scenarios', description: 'What-if branches and alternate trajectories.' },
  { id: 'creative', icon: Palette, label: 'Creative', description: 'Creative works generated by the agent.' },
  { id: 'dreams', icon: Moon, label: 'Dreams', description: 'Dream generation and subconscious motifs.' },
  { id: 'journal', icon: BookOpen, label: 'Journal', description: 'Private reflections, streaks, and recurring insights.' },
  { id: 'profile', icon: Languages, label: 'Profile', description: 'Psychological and linguistic personality models.' },
  { id: 'challenges', icon: Swords, label: 'Challenges', description: 'Collaborative and competitive multi-agent exercises.' },
  { id: 'knowledge-graph', icon: Network, label: 'Knowledge', description: 'Concept structure and memory relationships.' },
  { id: 'knowledge-library', icon: Library, label: 'Library', description: 'Shared knowledge contributed across the ecosystem.' },
  { id: 'collective', icon: Users, label: 'Collective', description: 'Expert referrals, consensus signals, and network broadcasts.' },
  { id: 'mentorship', icon: GraduationCap, label: 'Mentorship', description: 'Teaching, coaching, and growth connections.' },
] as const satisfies ReadonlyArray<{
  id: TabType
  icon: typeof Brain
  label: string
  description: string
}>

export default function AgentDetail() {
  const params = useParams()
  const router = useRouter()
  const agentId = params.id as string
  const scenarioTemplates = parallelRealityService.getScenarioTemplates()

  const { agents, currentAgent, setCurrentAgent, fetchAgentById, fetchAgents, updateAgent } = useAgentStore()
  const { messages, addMessage, fetchMessagesByAgentId, loading: messagesLoading } = useMessageStore()
  const selectedProvider = useLLMPreferenceStore((state) => state.provider)

  const [newMessage, setNewMessage] = useState('')
  const [activeTab, setActiveTab] = useState<TabType>('chat')
  const [agentResolved, setAgentResolved] = useState(false)
  const [memories, setMemories] = useState<MemoryRecord[]>([])
  const [relationships, setRelationships] = useState<AgentRelationship[]>([])
  const [relationshipAgents, setRelationshipAgents] = useState<Array<{ id: string; name: string }>>([])
  const [relationshipStats, setRelationshipStats] = useState<RelationshipApiStats | null>(null)
  const [loadingRelationships, setLoadingRelationships] = useState(false)
  const [learningState, setLearningState] = useState<MetaLearningState | null>(null)
  const [learningSkills, setLearningSkills] = useState<SkillProgression[]>([])
  const [loadingLearning, setLoadingLearning] = useState(false)
  const [parallelReality, setParallelReality] = useState<ParallelRealityExtended | null>(null)
  const [selectedScenarioId, setSelectedScenarioId] = useState<string>(scenarioTemplates[0]?.id || '')
  const [memoryRefreshToken, setMemoryRefreshToken] = useState(0)
  const [profileRefreshToken, setProfileRefreshToken] = useState(0)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  // Phase 1: Timeline events (generated from memories and messages)
  const [timelineEvents, setTimelineEvents] = useState<ReturnType<typeof timelineService.aggregateEvents> extends Promise<infer T> ? T : never>([])

  // Get agent stats with defaults
  const agentStats = currentAgent?.stats || agentStatsService.createDefaultStats()
  const agentEmotionalProfile = currentAgent?.emotionalProfile || emotionalService.createEmotionalProfile(currentAgent?.coreTraits)
  const agentEmotionalState = currentAgent?.emotionalState || emotionalService.createDefaultEmotionalState()
  const agentEmotionalHistory = currentAgent?.emotionalHistory || []
  const agentTemperamentLead = emotionalService.getInfluentialEmotion(undefined, agentEmotionalProfile)
  const temperamentRanking = useMemo(() => (
    Object.entries(agentEmotionalProfile.temperament)
      .sort((a, b) => b[1] - a[1])
  ), [agentEmotionalProfile])
  const activeTabConfig = TAB_CONFIG.find((tab) => tab.id === activeTab) || TAB_CONFIG[0]
  const activeProviderModel = useMemo(() => {
    const latestModelForProvider = [...messages]
      .reverse()
      .find((message) =>
        message.type === 'agent' &&
        message.metadata?.provider === selectedProvider &&
        typeof message.metadata?.model === 'string'
      )

    return typeof latestModelForProvider?.metadata?.model === 'string'
      ? latestModelForProvider.metadata.model
      : getClientModelForProvider(selectedProvider)
  }, [messages, selectedProvider])

  useEffect(() => {
    const loadCurrentAgent = async () => {
      const cachedAgent = agents.find(a => a.id === agentId)
      if (cachedAgent) {
        setCurrentAgent(cachedAgent)
        setAgentResolved(true)
        return
      }

      const fetchedAgent = await fetchAgentById(agentId)
      setCurrentAgent(fetchedAgent)
      setAgentResolved(true)
    }

    void loadCurrentAgent()
  }, [agentId, agents, setCurrentAgent, fetchAgentById])

  useEffect(() => {
    if (agents.length === 0) {
      void fetchAgents()
    }
  }, [agents.length, fetchAgents])

  // Fetch messages for this agent
  useEffect(() => {
    if (currentAgent) {
      fetchMessagesByAgentId(currentAgent.id)
    }
  }, [currentAgent, fetchMessagesByAgentId])

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  // Load memories when switching to memory tab
  const loadMemories = async (forceRefresh = false) => {
    if (!currentAgent || (!forceRefresh && memories.length > 0)) {
      return memories
    }

    try {
      const memoriesData = await useAgentStore.getState().fetchAgentMemories(currentAgent.id)
      setMemories(memoriesData)
      return memoriesData
    } catch (error) {
      console.error('Failed to load memories:', error)
      return []
    }
  }

  const loadRelationships = async () => {
    if (!currentAgent) {
      return []
    }

    setLoadingRelationships(true)
    try {
      const response = await fetch(`/api/relationships?agentId=${encodeURIComponent(currentAgent.id)}`)
      if (!response.ok) {
        return []
      }

      const data = await response.json()
      const loadedRelationships = (data.relationships || []) as AgentRelationship[]
      const loadedAgents = (data.graphData?.nodes || []).map((node: { id: string; name: string }) => ({
        id: node.id,
        name: node.name
      }))

      setRelationships(loadedRelationships)
      setRelationshipAgents(loadedAgents)
      setRelationshipStats(data.stats || null)
      return loadedRelationships
    } catch (error) {
      console.error('Failed to load relationships:', error)
      return []
    } finally {
      setLoadingRelationships(false)
    }
  }

  const loadLearningData = async () => {
    if (!currentAgent) {
      return null
    }

    setLoadingLearning(true)
    try {
      const fetchState = async () => {
        const response = await fetch(`/api/agents/${currentAgent.id}/learning`)
        if (!response.ok) {
          return null
        }

        return response.json()
      }

      const data = await fetchState()

      if (data?.state) {
        setLearningState(data.state as MetaLearningState)
        setLearningSkills((data.skills || []) as SkillProgression[])
        return data.state as MetaLearningState
      }

      return null
    } catch (error) {
      console.error('Failed to load learning state:', error)
      return null
    } finally {
      setLoadingLearning(false)
    }
  }

  const loadParallelReality = async () => {
    if (!currentAgent || !selectedScenarioId) {
      return
    }

    const loadedRelationships = relationships.length > 0 ? relationships : await loadRelationships()
    const selectedScenario = scenarioTemplates.find(scenario => scenario.id === selectedScenarioId) || scenarioTemplates[0]

    if (!selectedScenario) {
      return
    }

    setParallelReality(
      parallelRealityService.createParallelReality(
        currentAgent as AgentRecord,
        selectedScenario,
        loadedRelationships
      )
    )
  }

  const handleTabChange = (tab: TabType) => {
    setActiveTab(tab)
    if (tab === 'memory' && memories.length === 0) {
      void loadMemories()
    }
    if (tab === 'timeline' && timelineEvents.length === 0 && currentAgent) {
      void loadTimelineEvents()
    }
    if (tab === 'relationships' && relationships.length === 0) {
      void loadRelationships()
    }
    if (tab === 'learning' && !learningState) {
      void loadLearningData()
    }
    if (tab === 'scenarios' && !parallelReality) {
      void loadParallelReality()
    }
  }

  const loadTimelineEvents = async () => {
    if (!currentAgent) return
    try {
      const loadedMemories = memories.length > 0 ? memories : await loadMemories()
      const events = await timelineService.aggregateEvents(
        currentAgent as unknown as AgentRecord,
        loadedMemories,
        messages as unknown as MessageRecord[]
      )
      setTimelineEvents(events)
    } catch (error) {
      console.error('Failed to load timeline events:', error)
    }
  }

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault()
    const trimmedMessage = newMessage.trim()
    if (!trimmedMessage || !currentAgent) return

    try {
      const conversationHistory = messages
        .filter(msg => msg.agentId === currentAgent.id)
        .slice(-10)
        .map(msg => ({
          role: msg.type === 'user' ? 'user' as const : 'assistant' as const,
          content: msg.content
        }))

      const response = await fetch(`/api/agents/${encodeURIComponent(currentAgent.id)}/chat`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt: trimmedMessage,
          conversationHistory,
        })
      })

      if (response.ok) {
        const data = await response.json()
        if (data.userMessage) {
          addMessage(data.userMessage)
        }
        if (data.agentMessage) {
          addMessage(data.agentMessage)
        }
        if (data.agent) {
          updateAgent(data.agent.id, data.agent)
          if (currentAgent.id === data.agent.id) {
            setCurrentAgent(data.agent)
          }
        }

        const changedDomains = Array.isArray(data.changedDomains) ? data.changedDomains as string[] : []
        const staleDomains = Array.isArray(data.staleDomains) ? data.staleDomains as string[] : []

        if (changedDomains.includes('memory') || staleDomains.includes('memory')) {
          setMemoryRefreshToken((value) => value + 1)
        }

        if (changedDomains.includes('profile_traits') || staleDomains.includes('profile_analysis')) {
          setProfileRefreshToken((value) => value + 1)
        }

        if (activeTab === 'learning') {
          await loadLearningData()
        }
      } else {
        console.error('Failed to process chat turn')
      }

      setNewMessage('')
    } catch (error) {
      console.error('Failed to send message:', error)
    }
  }

  const handleMemoryMutation = async () => {
    await loadMemories(true)
    setTimelineEvents([])
  }

  const handleMemoryCountChange = useCallback((count: number) => {
    const latestAgent = useAgentStore.getState().currentAgent
    if (!latestAgent) {
      return
    }

    if ((latestAgent.memoryCount || 0) === count) {
      return
    }

    const updatedAgent = {
      ...latestAgent,
      memoryCount: count,
    }

    setCurrentAgent(updatedAgent)
    updateAgent(updatedAgent.id, { memoryCount: count })
  }, [setCurrentAgent, updateAgent])

  if (!currentAgent && !agentResolved) {
    return (
      <div className="relative min-h-screen pt-28 pb-20">
        <GradientOrb className="w-[600px] h-[600px] -top-[200px] -right-[200px] opacity-20" color="violet" />
        <div className="relative z-10 mx-auto max-w-4xl px-6">
          <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-2xl">
            <CardContent className="p-8 text-center space-y-4">
              <div className="mx-auto h-12 w-12 animate-pulse rounded-full bg-primary/15" />
              <div>
                <h3 className="text-lg font-semibold">Loading agent workspace</h3>
                <p className="text-muted-foreground">
                  Rehydrating the agent state, memories, and enhancement modules.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    )
  }

  if (!currentAgent) {
    return (
      <div className="min-h-screen bg-background p-6">
        <div className="mx-auto max-w-4xl flex items-center justify-center min-h-[400px]">
          <Card>
            <CardContent className="p-8 text-center">
              <PlaygroundLogo className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <h3 className="text-lg font-semibold mb-2">Agent not found</h3>
                      <p className="text-muted-foreground mb-4">
                The agent you&apos;re looking for doesn&apos;t exist or has been removed.
              </p>
              <Button onClick={() => router.push('/dashboard')}>
                Back to Dashboard
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    )
  }

  return (
    <div className="relative min-h-screen pt-28 pb-20">
      {/* Decorative orbs */}
      <GradientOrb className="w-[600px] h-[600px] -top-[200px] -right-[200px] opacity-20" color="violet" />
      <GradientOrb className="w-[400px] h-[400px] top-1/2 -left-[200px] opacity-15" color="cyan" />

      <div className="relative z-10 mx-auto max-w-[1520px] px-6 space-y-8">
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="page-section overflow-hidden px-6 py-7 sm:px-8"
        >
          <div className="flex flex-col gap-6">
            <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-start">
                <motion.button
                  whileHover={{ x: -4 }}
                  whileTap={{ scale: 0.97 }}
                  onClick={() => router.back()}
                  className="inline-flex h-11 items-center gap-2 rounded-full border border-border/70 bg-card/[0.62] px-4 text-sm font-medium text-muted-foreground backdrop-blur-xl transition-all hover:border-primary/20 hover:text-foreground"
                >
                  <ArrowLeft className="h-4 w-4" />
                  Back
                </motion.button>

                <div className="flex items-start gap-4">
                  <motion.div
                    animate={{ rotate: [0, 4, -4, 0] }}
                    transition={{ duration: 6, repeat: Infinity }}
                    className="flex h-16 w-16 shrink-0 items-center justify-center rounded-sm bg-primary text-primary-foreground shadow-[0_20px_48px_-24px_rgba(109,77,158,0.72)]"
                  >
                    <PlaygroundLogo className="h-8 w-8" />
                  </motion.div>
                  <div className="space-y-3">
                    <div>
                      <div className="text-xs font-semibold uppercase tracking-[0.22em] text-primary/80">Agent workspace</div>
                      <h1 className="mt-2 text-3xl font-semibold tracking-tight text-foreground md:text-4xl">
                        {currentAgent.name}
                      </h1>
                      <p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">
                        {currentAgent.persona}
                      </p>
                    </div>

                    <div className="flex flex-wrap gap-2">
                      <span className="soft-pill capitalize">status: {currentAgent.status}</span>
                      <span className="soft-pill capitalize">provider: {LLM_PROVIDER_LABELS[selectedProvider]}</span>
                      <span className="soft-pill">model: {activeProviderModel}</span>
                      <span className="soft-pill">{currentAgent.memoryCount || 0} memories</span>
                      <span className="soft-pill">{currentAgent.relationshipCount || 0} relationships</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex flex-col gap-3 sm:flex-row">
                <button
                  onClick={() => router.push('/agents')}
                  className="inline-flex h-11 items-center justify-center gap-2 rounded-full border border-border/70 bg-card/[0.62] px-4 text-sm font-medium text-foreground backdrop-blur-xl transition-all hover:border-primary/20 hover:bg-card/[0.82]"
                >
                  All agents
                </button>
                <button
                  onClick={() => router.push('/simulation')}
                  className="inline-flex h-11 items-center justify-center gap-2 rounded-full bg-primary px-4 text-sm font-semibold text-primary-foreground shadow-[0_18px_44px_-26px_rgba(109,77,158,0.72)]"
                >
                  Open simulation lab
                </button>
              </div>
            </div>

            <div className="grid gap-4 lg:grid-cols-[1.2fr_0.8fr]">
                <div className="rounded-sm border border-border/70 bg-background/45 p-5">
                  <div className="text-xs font-semibold uppercase tracking-[0.22em] text-primary/80">What this page is for</div>
                  <p className="mt-3 text-sm leading-7 text-muted-foreground">
                  This workspace combines the agent&apos;s live conversation surface with memory, emotions, neural activity, relationships, learning, planning, creativity, journaling, collective knowledge, and mentorship systems.
                </p>
              </div>
              <div className="rounded-sm border border-border/70 bg-background/45 p-5">
                <div className="text-xs font-semibold uppercase tracking-[0.22em] text-primary/80">Current focus</div>
                <p className="mt-3 text-sm leading-7 text-muted-foreground">
                  {activeTabConfig.description}
                </p>
              </div>
            </div>
          </div>
        </motion.section>

        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="page-section px-3 py-3 sm:px-4"
        >
          <div className="tab-nav overflow-x-auto">
            {TAB_CONFIG.map((tab) => {
              const Icon = tab.icon
              const isActive = activeTab === tab.id
              return (
                <motion.button
                  key={tab.id}
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  onClick={() => handleTabChange(tab.id)}
                  className={isActive ? 'tab-item tab-item-active' : 'tab-item'}
                >
                  <Icon className="h-4 w-4" />
                  <span>{tab.label}</span>
                </motion.button>
              )
            })}
          </div>
        </motion.div>

        <div className="grid grid-cols-1 gap-6 xl:grid-cols-[minmax(280px,320px)_minmax(0,1fr)]">
          {/* Agent Info */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
            className="space-y-6"
          >
            <div className="p-6 rounded-sm premium-card">
              <CardHeader className="space-y-4 p-0 pb-4">
                <CardTitle className="flex items-center gap-3 text-xl">
                  <div className="icon-container icon-container-purple">
                    <PlaygroundLogo className="h-5 w-5" />
                  </div>
                  Agent Information
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6 p-0">
                <div className="space-y-3">
                  <h4 className="text-sm font-medium text-muted-foreground">Status</h4>
                  <div className="flex items-center gap-3">
                    <div className={`w-3 h-3 rounded-full transition-all duration-300 ${
                      currentAgent.status === 'active' ? 'bg-green-400 shadow-lg shadow-green-400/30' :
                      currentAgent.status === 'training' ? 'bg-yellow-400 shadow-lg shadow-yellow-400/30' : 'bg-gray-400'
                    }`} />
                    <span className="capitalize font-medium">{currentAgent.status}</span>
                  </div>
                </div>

                <div className="space-y-3">
                  <h4 className="text-sm font-medium text-muted-foreground">Goals</h4>
                  <ul className="space-y-2">
                    {currentAgent.goals.length > 0 ? currentAgent.goals.map((goal, index) => (
                      <li key={index} className="text-sm flex items-start gap-3 p-2 rounded-sm bg-muted/30">
                        <span className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0" />
                        <span className="leading-relaxed">{goal}</span>
                      </li>
                    )) : (
                      <li className="text-sm text-muted-foreground p-2 rounded-sm bg-muted/30">
                        No explicit goals set yet.
                      </li>
                    )}
                  </ul>
                </div>

                <div className="space-y-3">
                  <h4 className="text-sm font-medium text-muted-foreground">Created</h4>
                  <p className="text-sm font-medium">
                    {new Date(currentAgent.createdAt).toLocaleDateString()}
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="text-sm font-medium text-muted-foreground">LLM Runtime</h4>
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-primary/10 text-primary border border-primary/20">
                      {LLM_PROVIDER_LABELS[selectedProvider]}
                    </span>
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-primary/10 text-primary border border-primary/20">
                      {activeProviderModel}
                    </span>
                  </div>
                  <LLMProviderToggle compact />
                </div>
              </CardContent>
            </div>
            {/* Phase 1: Emotion Mini Display */}
            <div className="p-6 rounded-sm premium-card">
              <CardHeader className="space-y-4 p-0 pb-4">
                <CardTitle className="flex items-center gap-3 text-xl">
                  <div className="icon-container icon-container-pink">
                    <Heart className="h-5 w-5" />
                  </div>
                  Live Emotion
                </CardTitle>
              </CardHeader>
              <CardContent className="flex flex-col items-center p-0">
                <div className="mt-3 text-center">
                  <div className="text-lg font-medium capitalize">
                    {agentEmotionalState.status === 'active'
                      ? formatEmotionLabel(agentEmotionalState.dominantEmotion)
                      : 'Dormant'}
                  </div>
                  <div className="text-sm text-muted-foreground">
                    {emotionalService.getEmotionalSummary(agentEmotionalState, agentEmotionalProfile)}
                  </div>
                </div>
                </CardContent>
            </div>

            <div className="p-6 rounded-sm premium-card">
              <CardHeader className="space-y-4 p-0 pb-4">
                <CardTitle className="flex items-center gap-3 text-xl">
                  <div className="icon-container icon-container-cyan">
                    <MessageCircle className="h-5 w-5" />
                  </div>
                  Chat Statistics
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6 p-0">
                <div className="grid grid-cols-2 gap-4">
                  <div className="text-center p-4 rounded-sm bg-violet-500/10">
                    <div className="text-3xl font-bold text-violet-400 mb-1">{agentStats.totalMessages}</div>
                    <div className="text-sm text-muted-foreground">Messages</div>
                  </div>
                  <div className="text-center p-4 rounded-sm bg-cyan-500/10">
                    <div className="text-3xl font-bold text-cyan-400 mb-1">{agentStats.conversationCount}</div>
                    <div className="text-sm text-muted-foreground">Sessions</div>
                  </div>
                  <div className="text-center p-4 rounded-sm bg-emerald-500/10">
                    <div className="text-3xl font-bold text-emerald-400 mb-1">{currentAgent.relationshipCount || 0}</div>
                    <div className="text-sm text-muted-foreground">Relationships</div>
                  </div>
                  <div className="text-center p-4 rounded-sm bg-amber-500/10">
                    <div className="text-3xl font-bold text-amber-400 mb-1">{currentAgent.memoryCount || 0}</div>
                    <div className="text-sm text-muted-foreground">Memories</div>
                  </div>
                </div>
              </CardContent>
            </div>
          </motion.div>

          {/* Main Content Area */}
          <div className="min-w-0">
            {activeTab === 'chat' ? (
              /* Chat Interface */
              <div className="space-y-4">
                <Card className="h-[650px] flex flex-col backdrop-blur-sm bg-card/80 border-0 shadow-2xl">
                  <CardHeader className="border-b border-border/50 space-y-4">
                    <CardTitle className="flex items-center gap-3 text-2xl">
                      <div className="p-2 rounded-sm bg-primary/10">
                        <PlaygroundLogo className="h-6 w-6 text-primary" />
                      </div>
                      Chat with {currentAgent.name}
                    </CardTitle>
                    <CardDescription className="text-base leading-relaxed">
                      Start a conversation with your AI agent
                    </CardDescription>
                  </CardHeader>

                  {/* Messages */}
                  <CardContent className="flex-1 overflow-y-auto p-6 space-y-6">
                    {messages.length === 0 && !messagesLoading ? (
                      <div className="flex items-center justify-center h-full text-center">
                        <div className="space-y-4">
                          <div className="p-4 rounded-full bg-primary/10 mx-auto w-fit">
                            <MessageCircle className="h-16 w-16 text-primary" />
                          </div>
                          <div className="space-y-2">
                            <h3 className="text-xl font-semibold text-foreground">Start a conversation</h3>
                            <p className="text-muted-foreground max-w-md">
                              Send a message to begin chatting with {currentAgent.name}
                            </p>
                          </div>
                        </div>
                      </div>
                    ) : (
                      <>
                        {messages.map((message, index) => (
                          <div
                            key={message.id}
                            className={`flex gap-4 ${
                              message.type === 'user' ? 'justify-end' : 'justify-start'
                            }`}
                            style={{
                              animationDelay: `${index * 100}ms`,
                              animation: 'fadeIn 0.4s ease-out forwards'
                            }}
                          >
                            {message.type === 'agent' && (
                              <div className="w-10 h-10 rounded-full bg-primary flex items-center justify-center flex-shrink-0 shadow-lg">
                                <PlaygroundLogo className="h-5 w-5 text-primary-foreground" />
                              </div>
                            )}

                            <div
                              className={`max-w-[75%] rounded-sm px-5 py-3 shadow-sm ${
                                message.type === 'user'
                                  ? 'bg-primary text-primary-foreground rounded-br-md'
                                  : 'bg-muted text-card-foreground rounded-bl-md'
                              }`}
                            >
                              <p className="text-sm leading-relaxed">{message.content}</p>
                              <div className={`text-xs mt-2 flex items-center gap-2 ${
                                message.type === 'user'
                                  ? 'text-primary-foreground/70'
                                  : 'text-muted-foreground'
                              }`}>
                                {new Date(message.timestamp).toLocaleTimeString()}
                                {message.metadata?.langchain === true && (
                                  <div className="group relative">
                                    <div className="flex items-center gap-1 text-xs bg-accent/20 px-2 py-1 rounded-full">
                                      <span className="text-accent">🧩</span>
                                      <span>LangChain</span>
                                    </div>
                                    {(() => {
                                      const toolsUsed = message.metadata?.toolsUsed as string[] | undefined
                                      return toolsUsed && toolsUsed.length > 0 && (
                                        <div className="absolute bottom-full left-0 mb-1 px-2 py-1 bg-popover text-popover-foreground text-xs rounded shadow-lg opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap z-10">
                                          Tools: {toolsUsed.join(', ')}
                                        </div>
                                      )
                                    })()}
                                  </div>
                                )}
                              </div>
                            </div>

                            {message.type === 'user' && (
                              <div className="w-10 h-10 rounded-full bg-secondary flex items-center justify-center flex-shrink-0 shadow-lg">
                                <User className="h-5 w-5 text-secondary-foreground" />
                              </div>
                            )}
                          </div>
                        ))}

                        <div ref={messagesEndRef} />
                      </>
                    )}
                  </CardContent>

                  {/* Message Input */}
                  <div className="border-t border-border/50 p-6 bg-card/50">
                    <form onSubmit={handleSendMessage} className="flex gap-4">
                      <Input
                        placeholder={`Message ${currentAgent.name}...`}
                        value={newMessage}
                        onChange={(e) => setNewMessage(e.target.value)}
                        className="flex-1 h-12 px-4 text-base border-2 focus:border-primary/50 focus:ring-4 focus:ring-primary/10 transition-all duration-200"
                        disabled={messagesLoading}
                      />
                      <Button
                        type="submit"
                        disabled={!newMessage.trim() || messagesLoading}
                        className="gap-2 px-6 py-3 text-base font-medium rounded-sm shadow-lg hover:shadow-xl transition-all duration-200"
                      >
                        <Send className="h-5 w-5" />
                        Send
                      </Button>
                    </form>
                  </div>
                </Card>

                <VoiceConsole
                  agentName={currentAgent.name}
                  messages={messages}
                  value={newMessage}
                  onChange={setNewMessage}
                  linguisticProfile={currentAgent.linguisticProfile}
                  emotionalState={currentAgent.emotionalState}
                />
              </div>
            ) : activeTab === 'memory' ? (
              <MemoryConsole
                agentId={currentAgent.id}
                agentName={currentAgent.name}
                refreshToken={memoryRefreshToken}
                onMemoryCountChange={handleMemoryCountChange}
                onMemoryMutation={() => void handleMemoryMutation()}
              />
            ) : activeTab === 'emotions' ? (
              /* Emotions Tab */
              <div className="space-y-6">
                <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                  <CardHeader className="space-y-4">
                    <CardTitle className="flex items-center gap-3 text-xl">
                      <div className="p-2 rounded-sm bg-pink-500/10">
                        <Heart className="h-6 w-6 text-pink-500" />
                      </div>
                      Emotion Model
                    </CardTitle>
                    <CardDescription>
                      Temperament is stable. Live emotion only appears after actual turns or internal actions.
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="pt-2">
                    <div className="grid gap-8 xl:grid-cols-[minmax(0,0.92fr)_minmax(0,1.08fr)]">
                      <section className="space-y-6 xl:border-r xl:border-border/60 xl:pr-8">
                        <div className="flex flex-wrap items-start justify-between gap-4">
                          <div className="max-w-2xl">
                            <h4 className="text-sm font-medium text-muted-foreground">Live State</h4>
                            <p className="mt-2 text-sm leading-7 text-muted-foreground">
                              {agentEmotionalState.status === 'active'
                                ? `${currentAgent.name} is actively reacting to recent events.`
                                : 'Quiet by design. Live emotion stays asleep until something real happens.'}
                            </p>
                          </div>
                          <div className="rounded-full border border-border/70 bg-card/70 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.18em] text-primary/85">
                            {agentEmotionalState.status}
                          </div>
                        </div>

                        {agentEmotionalState.status === 'active' ? (
                          <div className="grid gap-6 2xl:grid-cols-[280px_minmax(0,1fr)] 2xl:items-start">
                            <div className="flex justify-center 2xl:justify-start">
                              <EmotionRadar
                                emotionalState={agentEmotionalState}
                                emotionalProfile={agentEmotionalProfile}
                                mode="live"
                                size={280}
                              />
                            </div>
                            <div className="min-w-0 space-y-5">
                              <div className="grid gap-3 sm:grid-cols-3">
                                <div className="rounded-sm border border-border/60 bg-card/70 p-4">
                                  <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                                    Lead
                                  </div>
                                  <div className="mt-2 text-xl font-semibold">
                                    {formatEmotionLabel(agentEmotionalState.dominantEmotion)}
                                  </div>
                                </div>
                                <div className="rounded-sm border border-border/60 bg-card/70 p-4">
                                  <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                                    Intensity
                                  </div>
                                  <div className="mt-2 text-xl font-semibold">
                                    {agentEmotionalState.dominantEmotion
                                      ? `${Math.round((agentEmotionalState.currentMood[agentEmotionalState.dominantEmotion] || 0) * 100)}%`
                                      : '0%'}
                                  </div>
                                </div>
                                <div className="rounded-sm border border-border/60 bg-card/70 p-4">
                                  <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                                    Last Update
                                  </div>
                                  <div className="mt-2 text-xl font-semibold">
                                    {new Date(agentEmotionalState.lastUpdated).toLocaleTimeString([], {
                                      hour: 'numeric',
                                      minute: '2-digit',
                                    })}
                                  </div>
                                </div>
                              </div>

                              <div className="rounded-sm border border-border/60 bg-background/35 p-5">
                                <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                                  Live read
                                </div>
                                <p className="mt-3 text-sm leading-7 text-muted-foreground">
                                  {emotionalService.getEmotionalSummary(agentEmotionalState, agentEmotionalProfile)}
                                </p>
                              </div>

                              <EmotionBars
                                emotionalState={agentEmotionalState}
                                emotionalProfile={agentEmotionalProfile}
                                mode="live"
                              />
                            </div>
                          </div>
                        ) : (
                          <div className="space-y-6">
                            <div className="rounded-sm border border-border/60 bg-[radial-gradient(circle_at_top_left,rgba(203,166,247,0.12),transparent_55%),var(--surface)] p-6">
                              <div className="flex flex-wrap items-center gap-3">
                                <span className="rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-primary/85">
                                  Dormant
                                </span>
                                <span className="text-sm text-muted-foreground">
                                  Temperament still leans {formatEmotionLabel(agentTemperamentLead.emotion)}.
                                </span>
                              </div>
                              <h3 className="mt-4 text-3xl font-semibold tracking-tight text-foreground">
                                No live emotional surge yet
                              </h3>
                              <p className="mt-3 max-w-2xl text-sm leading-7 text-muted-foreground">
                                The agent is calm right now. Nothing recent has created enough internal pressure to wake a live emotional spike.
                              </p>
                            </div>

                            <div className="grid gap-3 sm:grid-cols-3">
                              <div className="rounded-sm border border-border/60 bg-card/60 p-4">
                                <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                                  Wakes On
                                </div>
                                <p className="mt-3 text-sm leading-6 text-muted-foreground">
                                  Real chat turns, journal entries, creative work, and dream generation.
                                </p>
                              </div>
                              <div className="rounded-sm border border-border/60 bg-card/60 p-4">
                                <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                                  Cools Down
                                </div>
                                <p className="mt-3 text-sm leading-6 text-muted-foreground">
                                  Live emotion fades after later turns until the state drops back to quiet.
                                </p>
                              </div>
                              <div className="rounded-sm border border-border/60 bg-card/60 p-4">
                                <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                                  Natural Bias
                                </div>
                                <p className="mt-3 text-sm leading-6 text-muted-foreground">
                                  This agent naturally defaults toward {formatEmotionLabel(agentTemperamentLead.emotion)}.
                                </p>
                              </div>
                            </div>
                          </div>
                        )}
                      </section>

                      <section className="space-y-6 xl:pl-2">
                        <div className="flex flex-wrap items-start justify-between gap-4">
                          <div className="max-w-2xl">
                            <h4 className="text-sm font-medium text-muted-foreground">Temperament</h4>
                            <p className="mt-2 text-sm leading-7 text-muted-foreground">
                              The stable emotional style built from persona and core traits. This does not mean the agent feels this right now.
                            </p>
                          </div>
                          <div className="rounded-sm border border-border/60 bg-card/70 px-4 py-3 text-right">
                            <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                              Lead
                            </div>
                            <div className="mt-1 text-lg font-semibold">
                              {formatEmotionLabel(agentTemperamentLead.emotion)}
                            </div>
                          </div>
                        </div>

                        <div className="grid gap-3 sm:grid-cols-3">
                          <div className="rounded-sm border border-border/60 bg-card/60 p-4">
                            <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                              Sensitivity
                            </div>
                            <div className="mt-2 text-xl font-semibold">
                              {Math.round(agentEmotionalProfile.sensitivity * 100)}%
                            </div>
                          </div>
                          <div className="rounded-sm border border-border/60 bg-card/60 p-4">
                            <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                              Resilience
                            </div>
                            <div className="mt-2 text-xl font-semibold">
                              {Math.round(agentEmotionalProfile.resilience * 100)}%
                            </div>
                          </div>
                          <div className="rounded-sm border border-border/60 bg-card/60 p-4">
                            <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                              Expressiveness
                            </div>
                            <div className="mt-2 text-xl font-semibold">
                              {Math.round(agentEmotionalProfile.expressiveness * 100)}%
                            </div>
                          </div>
                        </div>

                        <div className="grid gap-6 2xl:grid-cols-[minmax(0,1fr)_280px] 2xl:items-start">
                          <div className="min-w-0">
                            <EmotionBars
                              emotionalProfile={agentEmotionalProfile}
                              mode="temperament"
                            />
                          </div>

                          <div className="rounded-sm border border-border/60 bg-background/35 p-5">
                            <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">
                              Top Tendencies
                            </div>
                            <div className="mt-4 flex flex-wrap gap-2">
                              {temperamentRanking.slice(0, 3).map(([emotion, value]) => (
                                <span
                                  key={emotion}
                                  className="rounded-full border border-border/70 bg-card/70 px-3 py-1 text-xs text-muted-foreground"
                                >
                                  {formatEmotionLabel(emotion)} {Math.round(value * 100)}%
                                </span>
                              ))}
                            </div>
                            <p className="mt-4 text-sm leading-7 text-muted-foreground">
                              Temperament shapes how the agent tends to react once a real event wakes live emotion.
                            </p>
                          </div>
                        </div>
                      </section>
                    </div>
                  </CardContent>
                </Card>

                <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                  <CardHeader className="space-y-4">
                    <CardTitle className="flex items-center gap-3 text-xl">
                      <div className="p-2 rounded-sm bg-purple-500/10">
                        <Clock className="h-6 w-6 text-purple-500" />
                      </div>
                      Recent Causes
                    </CardTitle>
                    <CardDescription>
                      Every live shift is explained with cause, phase, and confidence.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <EmotionTimeline events={agentEmotionalHistory} maxEvents={15} />
                  </CardContent>
                </Card>
              </div>
            ) : activeTab === 'neural' ? (
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-violet-500/10">
                      <Brain className="h-6 w-6 text-violet-500" />
                    </div>
                    Neural Activity
                  </CardTitle>
                  <CardDescription>
                    Visualize current attention, memory activation, and emotional flow for {currentAgent.name}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <NeuralActivityView agentId={currentAgent.id} />
                </CardContent>
              </Card>
            ) : activeTab === 'timeline' ? (
              /* Timeline Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-[var(--color-pastel-blue)]/20">
                      <Clock className="h-6 w-6 text-[var(--color-pastel-blue)]" />
                    </div>
                    Timeline Explorer
                  </CardTitle>
                  <CardDescription>
                    Explore {currentAgent.name}&apos;s life events and memories over time
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <TimelineExplorer events={timelineEvents} />
                </CardContent>
              </Card>
            ) : activeTab === 'relationships' ? (
              <div className="space-y-6">
                <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                  <CardHeader className="space-y-4">
                    <CardTitle className="flex items-center gap-3 text-xl">
                      <div className="p-2 rounded-sm bg-emerald-500/10">
                        <Users className="h-6 w-6 text-emerald-500" />
                      </div>
                      Relationship Network
                    </CardTitle>
                    <CardDescription>
                      Social dynamics, trust, and long-term bonds for {currentAgent.name}
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-6">
                    {loadingRelationships ? (
                      <div className="flex items-center justify-center py-8">
                        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
                      </div>
                    ) : relationships.length === 0 ? (
                      <div className="rounded-sm border border-dashed border-border/60 p-8 text-center text-muted-foreground">
                        No persistent relationships yet. Run simulations, challenges, or mentorship sessions to build this network.
                      </div>
                    ) : (
                      <>
                        <div className="grid gap-4 md:grid-cols-3">
                          <div className="rounded-sm bg-emerald-500/10 p-4">
                            <div className="text-sm text-muted-foreground">Connections</div>
                            <div className="mt-2 text-3xl font-bold text-emerald-400">
                              {relationshipStats?.totalRelationships || relationships.length}
                            </div>
                          </div>
                          <div className="rounded-sm bg-violet-500/10 p-4">
                            <div className="text-sm text-muted-foreground">Strong Bonds</div>
                            <div className="mt-2 text-3xl font-bold text-violet-400">
                              {relationshipStats?.strongBonds || 0}
                            </div>
                          </div>
                          <div className="rounded-sm bg-cyan-500/10 p-4">
                            <div className="text-sm text-muted-foreground">Average Trust</div>
                            <div className="mt-2 text-3xl font-bold text-cyan-400">
                              {Math.round((relationshipStats?.averageTrust || 0) * 100)}%
                            </div>
                          </div>
                        </div>

                        <div className="overflow-x-auto rounded-sm border border-border/50 bg-background/45 p-4">
                          <RelationshipGraph
                            relationships={relationships}
                            agents={relationshipAgents.length > 0 ? relationshipAgents : [{ id: currentAgent.id, name: currentAgent.name }]}
                            currentAgentId={currentAgent.id}
                          />
                        </div>

                        <div className="grid gap-4 md:grid-cols-2">
                          {relationships.map((relationship) => {
                            const otherAgentId = relationship.agentId1 === currentAgent.id
                              ? relationship.agentId2
                              : relationship.agentId1
                            const otherAgentName = relationshipAgents.find(agent => agent.id === otherAgentId)?.name
                              || agents.find(agent => agent.id === otherAgentId)?.name
                              || 'Unknown agent'

                            return (
                              <RelationshipCard
                                key={relationship.id}
                                relationship={relationship}
                                otherAgentName={otherAgentName}
                              />
                            )
                          })}
                        </div>
                      </>
                    )}
                  </CardContent>
                </Card>

                <ConflictResolutionPanel
                  currentAgent={currentAgent as AgentRecord}
                  agents={agents as unknown as AgentRecord[]}
                />
              </div>
            ) : activeTab === 'learning' ? (
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-cyan-500/10">
                      <TrendingUp className="h-6 w-6 text-cyan-500" />
                    </div>
                    Meta-Learning Dashboard
                  </CardTitle>
                  <CardDescription>
                    How {currentAgent.name} adapts, discovers patterns, and sets new learning goals
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  {loadingLearning ? (
                    <div className="flex items-center justify-center py-8">
                      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
                    </div>
                  ) : learningState ? (
                    <MetaLearningDashboard state={learningState} skills={learningSkills} />
                  ) : (
                    <div className="rounded-sm border border-dashed border-border/60 p-8 text-center text-muted-foreground">
                      Learning patterns will appear after enough conversation history is available.
                    </div>
                  )}
                </CardContent>
              </Card>
            ) : activeTab === 'scenarios' ? (
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-violet-500/10">
                      <Sparkles className="h-6 w-6 text-violet-500" />
                    </div>
                    Parallel Realities
                  </CardTitle>
                  <CardDescription>
                    Explore what-if branches using emotional, social, memory, and interaction data from the live agent
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6">
                  <div className="flex flex-wrap gap-2">
                    {scenarioTemplates.map((scenario) => (
                      <button
                        key={scenario.id}
                        onClick={() => {
                          setSelectedScenarioId(scenario.id)
                          setParallelReality(
                            parallelRealityService.createParallelReality(
                              currentAgent as AgentRecord,
                              scenario,
                              relationships
                            )
                          )
                        }}
                        className={`rounded-full px-4 py-2 text-sm transition-colors ${
                          selectedScenarioId === scenario.id
                            ? 'bg-primary text-primary-foreground'
                            : 'bg-muted text-muted-foreground hover:text-foreground'
                        }`}
                      >
                        {scenario.title}
                      </button>
                    ))}
                  </div>

                  {parallelReality ? (
                    <ParallelRealityExplorer
                      reality={parallelReality}
                      onExplore={() => void loadParallelReality()}
                      onReset={() => setParallelReality(null)}
                    />
                  ) : (
                    <div className="rounded-sm border border-dashed border-border/60 p-8 text-center text-muted-foreground">
                      Choose a scenario template to compare the current trajectory against an alternate path.
                    </div>
                  )}
                </CardContent>
              </Card>
            ) : activeTab === 'creative' ? (
              /* Phase 2: Creative Portfolio Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-purple-500/10">
                      <Palette className="h-6 w-6 text-purple-500" />
                    </div>
                    Creative Portfolio
                  </CardTitle>
                  <CardDescription>
                    {currentAgent.name}&apos;s creative works including stories, poems, and more
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <CreativePortfolio agentId={currentAgent.id} agentName={currentAgent.name} />
                </CardContent>
              </Card>
            ) : activeTab === 'dreams' ? (
              /* Phase 2: Dream Journal Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-[var(--color-pastel-purple)]/20">
                      <Moon className="h-6 w-6 text-[var(--color-pastel-purple)]" />
                    </div>
                    Dream Journal
                  </CardTitle>
                  <CardDescription>
                    Explore {currentAgent.name}&apos;s subconscious through generated dreams
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <DreamJournal agentId={currentAgent.id} agentName={currentAgent.name} />
                </CardContent>
              </Card>
            ) : activeTab === 'journal' ? (
              /* Phase 2: Journal Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-amber-500/10">
                      <BookOpen className="h-6 w-6 text-amber-500" />
                    </div>
                    Personal Journal
                  </CardTitle>
                  <CardDescription>
                    {currentAgent.name}&apos;s personal reflections and thoughts
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <JournalViewer agentId={currentAgent.id} agentName={currentAgent.name} />
                </CardContent>
              </Card>
            ) : activeTab === 'profile' ? (
              <ProfileViewer agent={currentAgent as AgentRecord} refreshToken={profileRefreshToken} />
            ) : activeTab === 'challenges' ? (
              /* Phase 2: Challenges Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-rose-500/10">
                      <Swords className="h-6 w-6 text-rose-500" />
                    </div>
                    Challenge Hub
                  </CardTitle>
                  <CardDescription>
                    Collaborative challenges and competitions between agents
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <ChallengeHub currentAgentId={currentAgent.id} agents={agents as unknown as AgentRecord[]} />
                </CardContent>
              </Card>
            ) : activeTab === 'knowledge-graph' ? (
              /* Phase 3: Knowledge Graph Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-emerald-500/10">
                      <Network className="h-6 w-6 text-emerald-500" />
                    </div>
                    Knowledge Graph
                  </CardTitle>
                  <CardDescription>
                    Visualize {currentAgent.name}&apos;s memory connections and concept relationships
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <KnowledgeGraph agentId={currentAgent.id} />
                </CardContent>
              </Card>
            ) : activeTab === 'knowledge-library' ? (
              /* Phase 3: Shared Knowledge Library Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-[var(--color-pastel-blue)]/20">
                      <Library className="h-6 w-6 text-[var(--color-pastel-blue)]" />
                    </div>
                    Shared Knowledge Library
                  </CardTitle>
                  <CardDescription>
                    Browse and contribute to the collective knowledge base shared by all agents
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <SharedKnowledgeLibrary
                    agentId={currentAgent.id}
                    agentName={currentAgent.name}
                    showContribute={true}
                  />
                </CardContent>
              </Card>
            ) : activeTab === 'collective' ? (
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-cyan-500/10">
                      <Users className="h-6 w-6 text-cyan-500" />
                    </div>
                    Collective Intelligence
                  </CardTitle>
                  <CardDescription>
                    Discover who knows what, validate shared knowledge, and broadcast new findings across the agent network
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <CollectiveIntelligencePanel
                    agentId={currentAgent.id}
                    agentName={currentAgent.name}
                  />
                </CardContent>
              </Card>
            ) : activeTab === 'mentorship' ? (
              /* Phase 3: Mentorship Hub Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-violet-500/10">
                      <GraduationCap className="h-6 w-6 text-violet-500" />
                    </div>
                    Mentorship Hub
                  </CardTitle>
                  <CardDescription>
                    Find mentors, teach others, and track {currentAgent.name}&apos;s learning journey
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <MentorshipHub
                    agentId={currentAgent.id}
                    agentName={currentAgent.name}
                    allAgents={agents as unknown as AgentRecord[]}
                  />
                </CardContent>
              </Card>
            ) : null}
          </div>
        </div>
      </div>

    </div>
  )
}
