'use client'

import { cn } from '@/lib/utils'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useAgentStore } from '@/stores/agentStore'
import { useMessageStore } from '@/stores/messageStore'
import { MemoryRecord, MessageRecord, AgentRecord, ScenarioAnalyticsSummary, ScenarioBranchPoint, ScenarioIntervention, ScenarioRunRecord, EMOTION_COLORS, EmotionType, MessageRenderBlock, TimelineEvent, JournalEntry } from '@/types/database'
import { ArrowLeft, Send, User, MessageCircle, Brain, TrendingUp, Heart, Clock, Palette, Moon, BookOpen, Swords, Network, Library, GraduationCap, Users, Languages, Sparkles, LayoutDashboard } from 'lucide-react'
import { PlaygroundLogo } from '@/components/PlaygroundLogo'
import { motion } from 'framer-motion'
import { GradientOrb } from '@/components/ui/animated-background'
import { MetaLearningState, SkillProgression } from '@/types/metaLearning'

// Phase 1 Components
import { EmotionRadar, EmotionBars, EmotionRadarMini } from '@/components/emotions/EmotionRadar'
import { EmotionTimeline } from '@/components/emotions/EmotionTimeline'
import { TimelineExplorer } from '@/components/timeline/TimelineExplorer'

// Phase 2 Components
import { CreativeStudio } from '@/components/creative/CreativeStudio'
import { DreamJournal } from '@/components/dreams/DreamJournal'
import { JournalViewer } from '@/components/journal/JournalViewer'
import { ProfileViewer } from '@/components/profile/ProfileViewer'
import { MemoryConsole } from '@/components/memory/MemoryConsole'
import { ChallengeLab } from '@/components/challenges/ChallengeLab'
import { RelationshipWorkspace } from '@/components/relationships/RelationshipWorkspace'
import { MetaLearningDashboard } from '@/components/learning/MetaLearningDashboard'

import { ParallelRealityExplorer } from '@/components/parallel/ParallelRealityExplorer'
import { VoiceConsole } from '@/components/chat/VoiceConsole'
import { ChatMessageContent } from '@/components/chat/ChatMessageContent'

// Phase 3 Components
import { KnowledgeGraph } from '@/components/knowledge/KnowledgeGraph'
import { SharedKnowledgeLibrary } from '@/components/knowledge/SharedKnowledgeLibrary'
import { MentorshipHub } from '@/components/mentorship/MentorshipHub'
import { CollectiveIntelligencePanel } from '@/components/collective/CollectiveIntelligencePanel'
import { NeuralActivityView } from '@/components/neural/NeuralActivityView'
import { LLMProviderToggle } from '@/components/llm/LLMProviderToggle'
import { buildLLMPreferenceHeaders, getClientModelForProvider, LLM_PROVIDER_LABELS } from '@/lib/llm/clientPreference'
import { useLLMPreferenceStore } from '@/stores/llmPreferenceStore'

// Phase 1 Services
import { agentStatsService } from '@/lib/services/agentStatsService'
import { emotionalService } from '@/lib/services/emotionalService'
import { timelineService } from '@/lib/services/timelineService'

type TabType =
  | 'overview'
  | 'chat'
  | 'memory'
  | 'emotions'
  | 'neural'
  | 'timeline'
  | 'relationships'
  | 'learning'
  | 'scenarios'
  | 'creative'
  | 'dreams'
  | 'journal'
  | 'profile'
  | 'challenges'
  | 'knowledge-graph'
  | 'knowledge-library'
  | 'collective'
  | 'mentorship'

function formatEmotionLabel(emotion: string | null | undefined): string {
  if (!emotion) {
    return 'Dormant'
  }

  return emotion.charAt(0).toUpperCase() + emotion.slice(1)
}

const TAB_CONFIG = [
  { id: 'overview', icon: LayoutDashboard, label: 'Overview', description: 'Agent health, goals, and stats.' },
  { id: 'chat', icon: MessageCircle, label: 'Chat', description: 'Direct conversations and model responses.' },
  { id: 'emotions', icon: Heart, label: 'Emotions', description: 'Current emotional signals and recent shifts.' },
  { id: 'neural', icon: Brain, label: 'Neural', description: 'Live thought flow, attention, and emotional activity.' },
  { id: 'timeline', icon: Clock, label: 'Timeline', description: 'A chronological view of important events.' },
  { id: 'memory', icon: Brain, label: 'Memory', description: 'Stored memories, trait evolution, and retention stats.' },
  { id: 'relationships', icon: Users, label: 'Relationships', description: 'Trust, bonds, and long-term social state.' },
  { id: 'learning', icon: TrendingUp, label: 'Learning', description: 'Patterns, recommendations, and meta-learning signals.' },

  { id: 'scenarios', icon: Sparkles, label: 'Scenarios', description: 'What-if branches and alternate trajectories.' },
  { id: 'creative', icon: Palette, label: 'Creative', description: 'Creative works generated by the agent.' },
  { id: 'dreams', icon: Moon, label: 'Dreams', description: 'Dream generation and subconscious motifs.' },
  { id: 'journal', icon: BookOpen, label: 'Journal', description: 'Private reflections, streaks, and recurring insights.' },
  { id: 'profile', icon: Languages, label: 'Profile', description: 'Psychological and linguistic personality models.' },
  { id: 'challenges', icon: Swords, label: 'Challenges', description: 'Capability and relationship trials.' },
  { id: 'knowledge-graph', icon: Network, label: 'Knowledge', description: 'Concept structure and memory relationships.' },
  { id: 'knowledge-library', icon: Library, label: 'Library', description: 'Shared knowledge contributed across the ecosystem.' },
  { id: 'collective', icon: Users, label: 'Collective', description: 'Expert referrals, consensus signals, and network broadcasts.' },
  { id: 'mentorship', icon: GraduationCap, label: 'Mentorship', description: 'Teaching, coaching, and growth connections.' },
] as const satisfies ReadonlyArray<{
  id: TabType
  icon: typeof Brain
  label: string
  description: string
}>

export default function AgentDetail() {
  const params = useParams()
  const router = useRouter()
  const agentId = params.id as string

  const { agents, currentAgent, setCurrentAgent, fetchAgentById, fetchAgents, updateAgent } = useAgentStore()
  const { messages, addMessage, fetchMessagesByAgentId, loading: messagesLoading } = useMessageStore()
  const selectedProvider = useLLMPreferenceStore((state) => state.provider)

  const [newMessage, setNewMessage] = useState('')
  const [activeTab, setActiveTab] = useState<TabType>('overview')
  const [agentResolved, setAgentResolved] = useState(false)
  const [memories, setMemories] = useState<MemoryRecord[]>([])
  const [learningState, setLearningState] = useState<MetaLearningState | null>(null)
  const [learningSkills, setLearningSkills] = useState<SkillProgression[]>([])
  const [loadingLearning, setLoadingLearning] = useState(false)
  const [scenarioBranchPoints, setScenarioBranchPoints] = useState<ScenarioBranchPoint[]>([])
  const [scenarioTemplates, setScenarioTemplates] = useState<ScenarioIntervention[]>([])
  const [scenarioRuns, setScenarioRuns] = useState<ScenarioRunRecord[]>([])
  const [scenarioAnalytics, setScenarioAnalytics] = useState<ScenarioAnalyticsSummary | null>(null)
  const [activeScenarioRun, setActiveScenarioRun] = useState<ScenarioRunRecord | null>(null)
  const [selectedBranchPoint, setSelectedBranchPoint] = useState<ScenarioBranchPoint | null>(null)
  const [selectedIntervention, setSelectedIntervention] = useState<ScenarioIntervention | null>(null)
  const [runningScenario, setRunningScenario] = useState(false)
  const [memoryRefreshToken, setMemoryRefreshToken] = useState(0)
  const [profileRefreshToken, setProfileRefreshToken] = useState(0)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  // Phase 1: Timeline events (generated from memories and messages)
  const [timelineEvents, setTimelineEvents] = useState<TimelineEvent[]>([])

  // Get agent stats with defaults
  const agentStats = currentAgent?.stats || agentStatsService.createDefaultStats()
  const agentEmotionalProfile = currentAgent?.emotionalProfile || emotionalService.createEmotionalProfile(currentAgent?.coreTraits)
  const agentEmotionalState = currentAgent?.emotionalState || emotionalService.createDefaultEmotionalState()
  const agentEmotionalHistory = currentAgent?.emotionalHistory || []
  const agentTemperamentLead = emotionalService.getInfluentialEmotion(undefined, agentEmotionalProfile)
  const temperamentRanking = useMemo(() => (
    Object.entries(agentEmotionalProfile.temperament)
      .sort((a, b) => b[1] - a[1])
  ), [agentEmotionalProfile])
  const activeProviderModel = useMemo(() => {
    const latestModelForProvider = [...messages]
      .reverse()
      .find((message) =>
        message.type === 'agent' &&
        message.metadata?.provider === selectedProvider &&
        typeof message.metadata?.model === 'string'
      )

    return typeof latestModelForProvider?.metadata?.model === 'string'
      ? latestModelForProvider.metadata.model
      : getClientModelForProvider(selectedProvider)
  }, [messages, selectedProvider])

  useEffect(() => {
    const loadCurrentAgent = async () => {
      const cachedAgent = agents.find(a => a.id === agentId)
      if (cachedAgent) {
        setCurrentAgent(cachedAgent)
        setAgentResolved(true)
        return
      }

      const fetchedAgent = await fetchAgentById(agentId)
      setCurrentAgent(fetchedAgent)
      setAgentResolved(true)
    }

    void loadCurrentAgent()
  }, [agentId, agents, setCurrentAgent, fetchAgentById])

  useEffect(() => {
    if (agents.length === 0) {
      void fetchAgents()
    }
  }, [agents.length, fetchAgents])

  // Fetch messages for this agent
  useEffect(() => {
    if (currentAgent) {
      fetchMessagesByAgentId(currentAgent.id)
    }
  }, [currentAgent, fetchMessagesByAgentId])

  useEffect(() => {
    setScenarioBranchPoints([])
    setScenarioTemplates([])
    setScenarioRuns([])
    setScenarioAnalytics(null)
    setActiveScenarioRun(null)
    setSelectedBranchPoint(null)
    setSelectedIntervention(null)
  }, [currentAgent?.id])

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  // Load memories when switching to memory tab
  const loadMemories = async (forceRefresh = false) => {
    if (!currentAgent || (!forceRefresh && memories.length > 0)) {
      return memories
    }

    try {
      const memoriesData = await useAgentStore.getState().fetchAgentMemories(currentAgent.id)
      setMemories(memoriesData)
      return memoriesData
    } catch (error) {
      console.error('Failed to load memories:', error)
      return []
    }
  }

  const loadLearningData = async () => {
    if (!currentAgent) {
      return null
    }

    setLoadingLearning(true)
    try {
      const fetchState = async () => {
        const response = await fetch(`/api/agents/${currentAgent.id}/learning`)
        if (!response.ok) {
          return null
        }

        return response.json()
      }

      const data = await fetchState()

      if (data?.state) {
        setLearningState(data.state as MetaLearningState)
        setLearningSkills((data.skills || []) as SkillProgression[])
        return data.state as MetaLearningState
      }

      return null
    } catch (error) {
      console.error('Failed to load learning state:', error)
      return null
    } finally {
      setLoadingLearning(false)
    }
  }

  const loadScenarioLab = useCallback(async () => {
    if (!currentAgent) {
      return
    }

    try {
      const response = await fetch(`/api/scenarios?agentId=${encodeURIComponent(currentAgent.id)}`)
      if (!response.ok) {
        return
      }

      const data = await response.json()
      const nextBranchPoints = (data.branchPoints || []) as ScenarioBranchPoint[]
      const nextTemplates = (data.templates || []) as ScenarioIntervention[]
      const nextRuns = (data.recentRuns || []) as ScenarioRunRecord[]
      const nextAnalytics = (data.analytics || null) as ScenarioAnalyticsSummary | null

      setScenarioBranchPoints(nextBranchPoints)
      setScenarioTemplates(nextTemplates)
      setScenarioRuns(nextRuns)
      setScenarioAnalytics(nextAnalytics)
      setSelectedBranchPoint((current) => current || nextBranchPoints[0] || null)
      setSelectedIntervention((current) => current || nextTemplates[0] || null)
      setActiveScenarioRun((current) => current || nextRuns[0] || null)
    } catch (error) {
      console.error('Failed to load scenario lab:', error)
    }
  }, [currentAgent])

  const handleRunScenario = useCallback(async () => {
    if (!currentAgent || !selectedBranchPoint || !selectedIntervention) {
      return
    }

    setRunningScenario(true)
    try {
      const headers = new Headers(buildLLMPreferenceHeaders(selectedProvider, activeProviderModel))
      headers.set('Content-Type', 'application/json')

      const response = await fetch('/api/scenarios', {
        method: 'POST',
        headers,
        body: JSON.stringify({
          agentId: currentAgent.id,
          branchPointId: selectedBranchPoint.id,
          branchPointKind: selectedBranchPoint.kind,
          intervention: selectedIntervention,
          maxTurns: 3,
        }),
      })

      if (!response.ok) {
        throw new Error('Failed to run scenario')
      }

      const data = await response.json()
      const scenarioRun = data.scenarioRun as ScenarioRunRecord
      setActiveScenarioRun(scenarioRun)
      setScenarioRuns((previous) => [scenarioRun, ...previous.filter((entry) => entry.id !== scenarioRun.id)])
      await loadScenarioLab()
    } catch (error) {
      console.error('Failed to run scenario:', error)
    } finally {
      setRunningScenario(false)
    }
  }, [activeProviderModel, currentAgent, loadScenarioLab, selectedBranchPoint, selectedIntervention, selectedProvider])

  useEffect(() => {
    if (activeTab === 'scenarios' && currentAgent && scenarioBranchPoints.length === 0) {
      void loadScenarioLab()
    }
  }, [activeTab, currentAgent, loadScenarioLab, scenarioBranchPoints.length])

  const handleTabChange = (tab: TabType) => {
    setActiveTab(tab)
    if (tab === 'memory' && memories.length === 0) {
      void loadMemories()
    }
    if (tab === 'timeline' && timelineEvents.length === 0 && currentAgent) {
      void loadTimelineEvents()
    }
    if (tab === 'learning' && !learningState) {
      void loadLearningData()
    }
    if (tab === 'scenarios' && scenarioBranchPoints.length === 0) {
      void loadScenarioLab()
    }
  }

  const loadTimelineEvents = async () => {
    if (!currentAgent) return
    try {
      const loadedMemories = memories.length > 0 ? memories : await loadMemories()
      const [journalBootstrap, dreamBootstrap] = await Promise.all([
        fetch(`/api/agents/${currentAgent.id}/journal`, { cache: 'no-store' }),
        fetch(`/api/agents/${currentAgent.id}/dream`, { cache: 'no-store' }),
      ])
      const journalPayload = journalBootstrap.ok
        ? await journalBootstrap.json() as { recentSavedEntries?: JournalEntry[] }
        : null
      const dreamPayload = dreamBootstrap.ok
        ? await dreamBootstrap.json() as { recentSavedDreams?: import('@/types/database').Dream[] }
        : null
      const events = await timelineService.aggregateEvents(
        currentAgent as unknown as AgentRecord,
        loadedMemories,
        messages as unknown as MessageRecord[],
        dreamPayload?.recentSavedDreams || [],
        journalPayload?.recentSavedEntries || []
      )
      setTimelineEvents(events)
    } catch (error) {
      console.error('Failed to load timeline events:', error)
    }
  }

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault()
    const trimmedMessage = newMessage.trim()
    if (!trimmedMessage || !currentAgent) return

    try {
      const conversationHistory = messages
        .filter(msg => msg.agentId === currentAgent.id)
        .slice(-10)
        .map(msg => ({
          role: msg.type === 'user' ? 'user' as const : 'assistant' as const,
          content: msg.content
        }))

      const response = await fetch(`/api/agents/${encodeURIComponent(currentAgent.id)}/chat`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt: trimmedMessage,
          conversationHistory,
        })
      })

      if (response.ok) {
        const data = await response.json()
        if (data.userMessage) {
          addMessage(data.userMessage)
        }
        if (data.agentMessage) {
          addMessage(data.agentMessage)
        }
        if (data.agent) {
          updateAgent(data.agent.id, data.agent)
          if (currentAgent.id === data.agent.id) {
            setCurrentAgent(data.agent)
          }
        }

        const changedDomains = Array.isArray(data.changedDomains) ? data.changedDomains as string[] : []
        const staleDomains = Array.isArray(data.staleDomains) ? data.staleDomains as string[] : []

        if (changedDomains.includes('memory') || staleDomains.includes('memory')) {
          setMemoryRefreshToken((value) => value + 1)
        }

        if (changedDomains.includes('profile_traits') || staleDomains.includes('profile_analysis')) {
          setProfileRefreshToken((value) => value + 1)
        }

        if (activeTab === 'learning') {
          await loadLearningData()
        }
      } else {
        console.error('Failed to process chat turn')
      }

      setNewMessage('')
    } catch (error) {
      console.error('Failed to send message:', error)
    }
  }

  const handleMemoryMutation = async () => {
    await loadMemories(true)
    setTimelineEvents([])
  }

  const handleMemoryCountChange = useCallback((count: number) => {
    const latestAgent = useAgentStore.getState().currentAgent
    if (!latestAgent) {
      return
    }

    if ((latestAgent.memoryCount || 0) === count) {
      return
    }

    const updatedAgent = {
      ...latestAgent,
      memoryCount: count,
    }

    setCurrentAgent(updatedAgent)
    updateAgent(updatedAgent.id, { memoryCount: count })
  }, [setCurrentAgent, updateAgent])

  if (!currentAgent && !agentResolved) {
    return (
      <div className="relative min-h-screen pt-28 pb-20">
        <GradientOrb className="w-[600px] h-[600px] -top-[200px] -right-[200px] opacity-20" color="violet" />
        <div className="relative z-10 mx-auto max-w-4xl px-6">
          <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-2xl">
            <CardContent className="p-8 text-center space-y-4">
              <div className="mx-auto h-12 w-12 animate-pulse rounded-full bg-primary/15" />
              <div>
                <h3 className="text-lg font-semibold">Loading agent workspace</h3>
                <p className="text-muted-foreground">
                  Rehydrating the agent state, memories, and enhancement modules.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    )
  }

  if (!currentAgent) {
    return (
      <div className="min-h-screen bg-background p-6">
        <div className="mx-auto max-w-4xl flex items-center justify-center min-h-[400px]">
          <Card>
            <CardContent className="p-8 text-center">
              <PlaygroundLogo className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <h3 className="text-lg font-semibold mb-2">Agent not found</h3>
                      <p className="text-muted-foreground mb-4">
                The agent you&apos;re looking for doesn&apos;t exist or has been removed.
              </p>
              <Button onClick={() => router.push('/dashboard')}>
                Back to Dashboard
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    )
  }

  return (
    <div className="relative mt-4 min-h-screen overflow-x-hidden pt-4 pb-20">
      {/* Decorative orbs */}
      <GradientOrb className="w-[600px] h-[600px] -top-[200px] -right-[200px] opacity-20" color="violet" />
      <GradientOrb className="w-[400px] h-[400px] top-1/2 -left-[200px] opacity-15" color="cyan" />

      <div className="relative z-10 mx-auto w-full min-w-0 px-4 md:px-8">
        <div className="flex flex-col gap-6">
          {/* Main Dashboard Header */}
          <motion.header
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-surface/40 border border-border/40 p-6 rounded-sm backdrop-blur-xl flex flex-col lg:flex-row lg:items-center justify-between gap-6"
          >
            <div className="flex flex-col sm:flex-row sm:items-center gap-4">
              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-sm bg-primary/10 text-primary border border-primary/20 shadow-lg shadow-primary/5">
                <PlaygroundLogo className="h-6 w-6" />
              </div>
              <div>
                <div className="flex items-center gap-3 mb-1">
                  <h1 className="text-3xl font-black tracking-tighter text-foreground uppercase">
                    {currentAgent.name}
                  </h1>
                  <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20">
                    <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 animate-pulse" />
                    <span className="text-[9px] uppercase font-bold text-emerald-500 tracking-widest">{currentAgent.status}</span>
                  </div>
                </div>
                <p className="text-muted-foreground text-xs leading-relaxed lowercase italic opacity-70">
                  &quot;{currentAgent.persona}&quot;
                </p>
              </div>
            </div>

            <div className="flex flex-wrap items-center gap-3 lg:justify-end">
              <div className="flex items-center gap-4 px-4 py-2 bg-muted/20 border border-border/20 rounded-sm">
                <div className="flex flex-col">
                  <span className="text-[8px] font-bold text-muted-foreground uppercase tracking-[0.2em]">Context Nodes</span>
                  <span className="text-xs font-bold text-foreground">{currentAgent.memoryCount || 0}</span>
                </div>
                <div className="flex flex-col">
                  <span className="text-[8px] font-bold text-muted-foreground uppercase tracking-[0.2em]">Social Vectors</span>
                  <span className="text-xs font-bold text-foreground">{currentAgent.relationshipCount || 0}</span>
                </div>
                <div className="h-8 w-[1px] bg-border/20" />
                <div className="flex flex-col">
                  <span className="text-[8px] font-bold text-muted-foreground uppercase tracking-[0.2em]">Model Runtime</span>
                  <span className="text-xs font-bold text-foreground truncate max-w-[120px]">{activeProviderModel}</span>
                </div>
              </div>
              
              <div className="flex gap-2">
                <button 
                  onClick={() => router.back()}
                  className="px-4 h-10 rounded-sm border border-border/60 text-[10px] font-bold uppercase tracking-widest text-muted-foreground hover:bg-surface-strong transition-all flex items-center gap-2"
                >
                  <ArrowLeft className="h-3 w-3" /> Exit
                </button>
              </div>
            </div>
          </motion.header>

          {/* Horizontal Navigation Row */}
          <nav className="sticky top-2 z-50 bg-surface/80 border border-border/40 p-1 rounded-sm backdrop-blur-xl shadow-xl shadow-background/20 w-full overflow-hidden">
            <div className="flex items-center gap-6 px-4 overflow-x-auto scrollbar-none no-scrollbar py-1">
              {[
                { label: 'Core', items: ['overview', 'chat', 'emotions', 'neural', 'timeline', 'memory', 'relationships', 'learning'] },
                { label: 'Generative', items: ['scenarios', 'creative', 'dreams', 'journal'] },
                { label: 'Intelligence', items: ['profile', 'challenges', 'knowledge-graph', 'knowledge-library', 'collective', 'mentorship'] }
              ].map((group, idx) => (
                <div key={group.label} className="flex items-center gap-1 shrink-0">
                  <div className="text-[9px] uppercase font-black tracking-[0.25em] text-muted-foreground/30 mr-3 select-none">
                    {group.label}
                  </div>
                  <div className="flex items-center gap-1">
                    {TAB_CONFIG.filter(t => group.items.includes(t.id)).map((tab) => {
                      const Icon = tab.icon
                      const isActive = activeTab === tab.id
                      return (
                        <button
                          key={tab.id}
                          onClick={() => handleTabChange(tab.id)}
                          className={cn(
                            "flex items-center gap-2 px-3 py-1.5 rounded-sm transition-all duration-200 group relative whitespace-nowrap",
                            isActive 
                              ? "bg-primary text-primary-foreground shadow-md shadow-primary/20" 
                              : "text-muted-foreground/80 hover:bg-surface-strong hover:text-foreground"
                          )}
                        >
                          <Icon className={cn("h-3.5 w-3.5", isActive ? "text-white" : "text-primary/50 group-hover:text-primary")} />
                          <span className="text-[11px] font-bold uppercase tracking-wider">{tab.label}</span>
                          {isActive && (
                            <motion.div layoutId="nav-active" className="absolute -bottom-1 left-2 right-2 h-0.5 bg-white/30 rounded-full" />
                          )}
                        </button>
                      )
                    })}
                  </div>
                  {idx < 2 && <div className="ml-5 h-6 w-[1px] bg-border/20" />}
                </div>
              ))}
            </div>
          </nav>

          {/* Main Dashboard Surface */}
          <main className="min-w-0 space-y-6">

        <div className="flex flex-col gap-6">
          {/* Agent Info - Overview Tab Only */}
          {activeTab === 'overview' && (
            <motion.div
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="grid grid-cols-1 lg:grid-cols-3 gap-6"
            >
            <div className="p-6 rounded-sm premium-card">
              <CardHeader className="space-y-4 p-0 pb-4">
                <CardTitle className="flex items-center gap-3 text-xl">
                  <div className="icon-container icon-container-purple">
                    <PlaygroundLogo className="h-5 w-5" />
                  </div>
                  Agent Information
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6 p-0">
                <div className="space-y-3">
                  <h4 className="text-sm font-medium text-muted-foreground">Status</h4>
                  <div className="flex items-center gap-3">
                    <div className={`w-3 h-3 rounded-full transition-all duration-300 ${
                      currentAgent.status === 'active' ? 'bg-green-400 shadow-lg shadow-green-400/30' :
                      currentAgent.status === 'training' ? 'bg-yellow-400 shadow-lg shadow-yellow-400/30' : 'bg-gray-400'
                    }`} />
                    <span className="capitalize font-medium">{currentAgent.status}</span>
                  </div>
                </div>

                <div className="space-y-3">
                  <h4 className="text-sm font-medium text-muted-foreground">Goals</h4>
                  <ul className="space-y-2">
                    {currentAgent.goals.length > 0 ? currentAgent.goals.map((goal, index) => (
                      <li key={index} className="text-sm flex items-start gap-3 p-2 rounded-sm bg-muted/30">
                        <span className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0" />
                        <span className="leading-relaxed">{goal}</span>
                      </li>
                    )) : (
                      <li className="text-sm text-muted-foreground p-2 rounded-sm bg-muted/30">
                        No explicit goals set yet.
                      </li>
                    )}
                  </ul>
                </div>

                <div className="space-y-3">
                  <h4 className="text-sm font-medium text-muted-foreground">Created</h4>
                  <p className="text-sm font-medium">
                    {new Date(currentAgent.createdAt).toLocaleDateString()}
                  </p>
                </div>

                <div className="space-y-3">
                  <h4 className="text-sm font-medium text-muted-foreground">LLM Runtime</h4>
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-primary/10 text-primary border border-primary/20">
                      {LLM_PROVIDER_LABELS[selectedProvider]}
                    </span>
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-primary/10 text-primary border border-primary/20">
                      {activeProviderModel}
                    </span>
                  </div>
                  <LLMProviderToggle compact />
                </div>
              </CardContent>
            </div>
            {/* Phase 1: Emotion Mini Display */}
            <div className="p-6 rounded-sm premium-card">
              <CardHeader className="space-y-4 p-0 pb-4">
                <CardTitle className="flex items-center gap-3 text-xl">
                  <div className="icon-container icon-container-pink">
                    <Heart className="h-5 w-5" />
                  </div>
                  Live Emotion
                </CardTitle>
              </CardHeader>
              <CardContent className="flex flex-col items-center p-0">
                <div className="relative mb-4 flex justify-center">
                  <div className="absolute inset-0 scale-75 blur-2xl bg-pink-500/10 rounded-full" />
                  <EmotionRadarMini
                    emotionalState={agentEmotionalState}
                    emotionalProfile={agentEmotionalProfile}
                    size={110}
                  />
                </div>
                <div className="text-center">
                  <div className="text-lg font-medium capitalize">
                    {agentEmotionalState.status === 'active'
                      ? formatEmotionLabel(agentEmotionalState.dominantEmotion)
                      : 'Dormant'}
                  </div>
                  <div className="mt-2 text-xs leading-relaxed text-muted-foreground line-clamp-2">
                    {emotionalService.getEmotionalSummary(agentEmotionalState, agentEmotionalProfile)}
                  </div>
                </div>
              </CardContent>
            </div>

            <div className="p-6 rounded-sm premium-card">
              <CardHeader className="space-y-4 p-0 pb-4">
                <CardTitle className="flex items-center gap-3 text-xl">
                  <div className="icon-container icon-container-cyan">
                    <MessageCircle className="h-5 w-5" />
                  </div>
                  Chat Statistics
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6 p-0">
                <div className="grid grid-cols-2 gap-4">
                  <div className="text-center p-4 rounded-sm bg-violet-500/10">
                    <div className="text-3xl font-bold text-violet-400 mb-1">{agentStats.totalMessages}</div>
                    <div className="text-sm text-muted-foreground">Messages</div>
                  </div>
                  <div className="text-center p-4 rounded-sm bg-cyan-500/10">
                    <div className="text-3xl font-bold text-cyan-400 mb-1">{agentStats.conversationCount}</div>
                    <div className="text-sm text-muted-foreground">Sessions</div>
                  </div>
                  <div className="text-center p-4 rounded-sm bg-emerald-500/10">
                    <div className="text-3xl font-bold text-emerald-400 mb-1">{currentAgent.relationshipCount || 0}</div>
                    <div className="text-sm text-muted-foreground">Relationships</div>
                  </div>
                  <div className="text-center p-4 rounded-sm bg-amber-500/10">
                    <div className="text-3xl font-bold text-amber-400 mb-1">{currentAgent.memoryCount || 0}</div>
                    <div className="text-sm text-muted-foreground">Memories</div>
                  </div>
                </div>
              </CardContent>
            </div>
            </motion.div>
          )}

          {/* Main Content Area */}
          <div className="min-w-0">
            {activeTab === 'chat' ? (
              /* Chat Interface */
              <div className="space-y-4">
                <Card className="h-[650px] flex flex-col backdrop-blur-sm bg-card/80 border-0 shadow-2xl">
                  <CardHeader className="border-b border-border/50 space-y-4">
                    <CardTitle className="flex items-center gap-3 text-2xl">
                      <div className="p-2 rounded-sm bg-primary/10">
                        <PlaygroundLogo className="h-6 w-6 text-primary" />
                      </div>
                      Chat with {currentAgent.name}
                    </CardTitle>
                    <CardDescription className="text-base leading-relaxed">
                      Start a conversation with your AI agent
                    </CardDescription>
                  </CardHeader>

                  {/* Messages */}
                  <CardContent className="flex-1 overflow-y-auto p-6 space-y-6">
                    {messages.length === 0 && !messagesLoading ? (
                      <div className="flex items-center justify-center h-full text-center">
                        <div className="space-y-4">
                          <div className="p-4 rounded-full bg-primary/10 mx-auto w-fit">
                            <MessageCircle className="h-16 w-16 text-primary" />
                          </div>
                          <div className="space-y-2">
                            <h3 className="text-xl font-semibold text-foreground">Start a conversation</h3>
                            <p className="text-muted-foreground max-w-md">
                              Send a message to begin chatting with {currentAgent.name}
                            </p>
                          </div>
                        </div>
                      </div>
                    ) : (
                      <>
                        {messages.map((message, index) => (
                          <div
                            key={message.id}
                            className={`flex gap-4 ${
                              message.type === 'user' ? 'justify-end' : 'justify-start'
                            }`}
                            style={{
                              animationDelay: `${index * 100}ms`,
                              animation: 'fadeIn 0.4s ease-out forwards'
                            }}
                          >
                            {message.type === 'agent' && (
                              <div className="w-10 h-10 rounded-full bg-primary flex items-center justify-center flex-shrink-0 shadow-lg">
                                <PlaygroundLogo className="h-5 w-5 text-primary-foreground" />
                              </div>
                            )}

                            <div
                              className={`max-w-[75%] rounded-sm px-5 py-4 shadow-sm ${
                                message.type === 'user'
                                  ? 'bg-primary text-primary-foreground rounded-br-md'
                                  : 'bg-muted text-card-foreground rounded-bl-md'
                              }`}
                            >
                              <ChatMessageContent
                                content={message.content}
                                blocks={Array.isArray(message.metadata?.render?.blocks)
                                  ? message.metadata.render.blocks as MessageRenderBlock[]
                                  : undefined}
                                variant={message.type === 'user' ? 'user' : 'assistant'}
                              />
                              <div className={`text-xs mt-2 flex items-center gap-2 ${
                                message.type === 'user'
                                  ? 'text-primary-foreground/70'
                                  : 'text-muted-foreground'
                              }`}>
                                {new Date(message.timestamp).toLocaleTimeString()}
                                {message.metadata?.langchain === true && (
                                  <div className="group relative">
                                    <div className="flex items-center gap-1 text-xs bg-accent/20 px-2 py-1 rounded-full">
                                      <span className="text-accent">🧩</span>
                                      <span>LangChain</span>
                                    </div>
                                    {(() => {
                                      const toolsUsed = message.metadata?.toolsUsed as string[] | undefined
                                      return toolsUsed && toolsUsed.length > 0 && (
                                        <div className="absolute bottom-full left-0 mb-1 px-2 py-1 bg-popover text-popover-foreground text-xs rounded shadow-lg opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap z-10">
                                          Tools: {toolsUsed.join(', ')}
                                        </div>
                                      )
                                    })()}
                                  </div>
                                )}
                              </div>
                            </div>

                            {message.type === 'user' && (
                              <div className="w-10 h-10 rounded-full bg-secondary flex items-center justify-center flex-shrink-0 shadow-lg">
                                <User className="h-5 w-5 text-secondary-foreground" />
                              </div>
                            )}
                          </div>
                        ))}

                        <div ref={messagesEndRef} />
                      </>
                    )}
                  </CardContent>

                  {/* Message Input */}
                  <div className="border-t border-border/50 p-6 bg-card/50">
                    <form onSubmit={handleSendMessage} className="flex gap-4">
                      <Input
                        placeholder={`Message ${currentAgent.name}...`}
                        value={newMessage}
                        onChange={(e) => setNewMessage(e.target.value)}
                        className="flex-1 h-12 px-4 text-base border-2 focus:border-primary/50 focus:ring-4 focus:ring-primary/10 transition-all duration-200"
                        disabled={messagesLoading}
                      />
                      <Button
                        type="submit"
                        disabled={!newMessage.trim() || messagesLoading}
                        className="gap-2 px-6 py-3 text-base font-medium rounded-sm shadow-lg hover:shadow-xl transition-all duration-200"
                      >
                        <Send className="h-5 w-5" />
                        Send
                      </Button>
                    </form>
                  </div>
                </Card>

                <VoiceConsole
                  agentName={currentAgent.name}
                  messages={messages}
                  value={newMessage}
                  onChange={setNewMessage}
                  linguisticProfile={currentAgent.linguisticProfile}
                  emotionalState={currentAgent.emotionalState}
                />
              </div>
            ) : activeTab === 'memory' ? (
              <MemoryConsole
                agentId={currentAgent.id}
                agentName={currentAgent.name}
                refreshToken={memoryRefreshToken}
                onMemoryCountChange={handleMemoryCountChange}
                onMemoryMutation={() => void handleMemoryMutation()}
              />
            ) : activeTab === 'emotions' ? (
              /* Emotions Tab */
              <div className="space-y-6">
                <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                  <CardHeader className="space-y-4">
                    <CardTitle className="flex items-center gap-3 text-xl">
                      <div className="p-2 rounded-sm bg-pink-500/10">
                        <Heart className="h-6 w-6 text-pink-500" />
                      </div>
                      Emotion Model
                    </CardTitle>
                    <CardDescription>
                      Temperament is stable. Live emotion only appears after actual turns or internal actions.
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="p-6 sm:p-8">
                    <div className="flex flex-col gap-12">
                      {/* Section 1: Live Emotional Surge */}
                      <section className="space-y-8">
                        <div className="flex items-end justify-between border-b border-border/40 pb-4">
                          <div>
                            <h3 className="text-xl font-semibold tracking-tight">Live Emotional Signal</h3>
                            <p className="mt-1 text-sm text-muted-foreground">
                              {agentEmotionalState.status === 'active'
                                ? `Current emotional resonance for ${currentAgent.name}`
                                : 'System is currently in a state of emotional equilibrium'}
                            </p>
                          </div>
                          <div className={`rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-widest ring-1 ring-inset ${
                            agentEmotionalState.status === 'active' 
                              ? 'bg-emerald-500/10 text-emerald-400 ring-emerald-500/20' 
                              : 'bg-muted/50 text-muted-foreground ring-border'
                          }`}>
                            {agentEmotionalState.status}
                          </div>
                        </div>

                        {agentEmotionalState.status === 'active' ? (
                          <div className="grid gap-10 xl:grid-cols-[320px_1fr]">
                            <div className="flex flex-col items-center gap-6 rounded-sm bg-muted/20 p-6 ring-1 ring-border/50">
                              <EmotionRadar
                                emotionalState={agentEmotionalState}
                                emotionalProfile={agentEmotionalProfile}
                                recentEvents={agentEmotionalHistory}
                                mode="live"
                                size={280}
                              />
                            </div>

                            <div className="flex flex-col gap-8">
                              <div className="grid gap-4 sm:grid-cols-3">
                                <div className="rounded-sm bg-card/40 p-5 ring-1 ring-border/60 transition-colors hover:bg-card/60">
                                  <div className="text-[10px] font-bold uppercase tracking-widest text-primary/70">Dominant</div>
                                  <div className="mt-2 text-2xl font-semibold tracking-tight">
                                    {formatEmotionLabel(agentEmotionalState.dominantEmotion)}
                                  </div>
                                </div>
                                <div className="rounded-sm bg-card/40 p-5 ring-1 ring-border/60 transition-colors hover:bg-card/60">
                                  <div className="text-[10px] font-bold uppercase tracking-widest text-primary/70">Intensity</div>
                                  <div className="mt-2 text-2xl font-semibold tracking-tight">
                                    {agentEmotionalState.dominantEmotion
                                      ? `${Math.round((agentEmotionalState.currentMood[agentEmotionalState.dominantEmotion] || 0) * 100)}%`
                                      : '0%'}
                                  </div>
                                </div>
                                <div className="rounded-sm bg-card/40 p-5 ring-1 ring-border/60 transition-colors hover:bg-card/60">
                                  <div className="text-[10px] font-bold uppercase tracking-widest text-primary/70">Last Pulse</div>
                                  <div className="mt-2 text-2xl font-semibold tracking-tight">
                                    {new Date(agentEmotionalState.lastUpdated).toLocaleTimeString([], {
                                      hour: 'numeric',
                                      minute: '2-digit',
                                    })}
                                  </div>
                                </div>
                              </div>

                              <div className="rounded-sm border-l-2 border-primary/40 bg-primary/5 p-5">
                                <div className="text-[10px] font-bold uppercase tracking-widest text-primary/80">Active Analysis</div>
                                <p className="mt-2 text-sm leading-relaxed text-foreground/90 italic">
                                  &quot;{emotionalService.getEmotionalSummary(agentEmotionalState, agentEmotionalProfile)}&quot;
                                </p>
                              </div>

                              <div className="space-y-4">
                                <h4 className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Detailed Spectrum</h4>
                                <EmotionBars
                                  emotionalState={agentEmotionalState}
                                  emotionalProfile={agentEmotionalProfile}
                                  mode="live"
                                />
                              </div>
                            </div>
                          </div>
                        ) : (
                          <div className="rounded-sm bg-muted/20 p-10 text-center ring-1 ring-border/50">
                            <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-muted/40 text-muted-foreground mb-4">
                              <Heart className="h-8 w-8 opacity-20" />
                            </div>
                            <h3 className="text-lg font-medium text-foreground">Emotional baseline is stable</h3>
                            <p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">
                              {currentAgent.name} is currently in a dormant emotional state. Live signals will emerge when new events trigger internal processing.
                            </p>
                          </div>
                        )}
                      </section>

                      {/* Section 2: Emotional Temperament */}
                      <section className="space-y-8">
                        <div className="flex items-end justify-between border-b border-border/40 pb-4">
                          <div>
                            <h3 className="text-xl font-semibold tracking-tight">Psychological Foundation</h3>
                            <p className="mt-1 text-sm text-muted-foreground">
                              The underlying emotional architecture and natural biases of this agent
                            </p>
                          </div>
                          <div className="rounded-full bg-primary/10 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-primary ring-1 ring-inset ring-primary/20">
                            Fixed Profile
                          </div>
                        </div>

                        <div className="grid gap-10 xl:grid-cols-2">
                          <div className="space-y-8">
                            <div className="grid gap-4 sm:grid-cols-3">
                              <div className="rounded-sm bg-card/40 p-5 ring-1 ring-border/60">
                                <div className="text-[10px] font-bold uppercase tracking-widest text-primary/70">Sensitivity</div>
                                <div className="mt-2 text-2xl font-semibold tracking-tight tabular-nums">
                                  {Math.round(agentEmotionalProfile.sensitivity * 100)}%
                                </div>
                              </div>
                              <div className="rounded-sm bg-card/40 p-5 ring-1 ring-border/60">
                                <div className="text-[10px] font-bold uppercase tracking-widest text-primary/70">Resilience</div>
                                <div className="mt-2 text-2xl font-semibold tracking-tight tabular-nums">
                                  {Math.round(agentEmotionalProfile.resilience * 100)}%
                                </div>
                              </div>
                              <div className="rounded-sm bg-card/40 p-5 ring-1 ring-border/60">
                                <div className="text-[10px] font-bold uppercase tracking-widest text-primary/70">Expressive</div>
                                <div className="mt-2 text-2xl font-semibold tracking-tight tabular-nums">
                                  {Math.round(agentEmotionalProfile.expressiveness * 100)}%
                                </div>
                              </div>
                            </div>

                            <div className="rounded-sm bg-background/50 p-6 shadow-inner ring-1 ring-border/40">
                              <h4 className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground mb-4">Core Temperament</h4>
                              <EmotionBars
                                emotionalProfile={agentEmotionalProfile}
                                mode="temperament"
                              />
                            </div>
                          </div>

                          <div className="flex flex-col gap-8">
                            <div className="rounded-sm bg-card/40 p-6 ring-1 ring-border/60">
                              <div className="flex items-center justify-between">
                                <h4 className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Bias Distribution</h4>
                                <span className="text-[10px] font-medium text-primary">Top 3 Propensities</span>
                              </div>
                              <div className="mt-6 flex flex-wrap gap-3">
                                {temperamentRanking.slice(0, 3).map(([emotion, value]) => (
                                  <div
                                    key={emotion}
                                    className="flex items-center gap-2 rounded-full bg-background/80 px-4 py-2 text-xs font-medium ring-1 ring-border shadow-sm"
                                  >
                                    <div className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: EMOTION_COLORS[emotion as EmotionType] }} />
                                    <span className="text-foreground/80">{formatEmotionLabel(emotion)}</span>
                                    <span className="ml-1 font-mono text-[10px] text-muted-foreground">{(value * 100).toFixed(0)}%</span>
                                  </div>
                                ))}
                              </div>
                              <p className="mt-6 text-sm leading-relaxed text-muted-foreground italic">
                                This profile determines how the agent naturally reacts. It defaults to {formatEmotionLabel(agentTemperamentLead.emotion)} when unstressed.
                              </p>
                            </div>

                            <div className="flex-1 rounded-sm border border-dashed border-border/80 bg-muted/10 p-8 flex flex-col items-center justify-center text-center">
                              <div className="p-3 rounded-full bg-background ring-1 ring-border shadow-sm mb-4">
                                <Brain className="h-6 w-6 text-primary" />
                              </div>
                              <p className="text-xs font-medium text-muted-foreground leading-relaxed max-w-[240px]">
                                Temperament is shaped by the agent&apos;s persona and core traits.
                              </p>
                            </div>
                          </div>
                        </div>
                      </section>
                    </div>
                  </CardContent>
                </Card>

                <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                  <CardHeader className="space-y-4">
                    <CardTitle className="flex items-center gap-3 text-xl">
                      <div className="p-2 rounded-sm bg-purple-500/10">
                        <Clock className="h-6 w-6 text-purple-500" />
                      </div>
                      Recent Causes
                    </CardTitle>
                    <CardDescription>
                      Every live shift is explained with cause, phase, confidence, linked evidence refs, and downstream hints for journal, dream, and scenario behavior.
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <EmotionTimeline events={agentEmotionalHistory} maxEvents={15} />
                  </CardContent>
                </Card>
              </div>
            ) : activeTab === 'neural' ? (
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-violet-500/10">
                      <Brain className="h-6 w-6 text-violet-500" />
                    </div>
                    Neural Activity
                  </CardTitle>
                  <CardDescription>
                    Visualize current attention, memory activation, and emotional flow for {currentAgent.name}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <NeuralActivityView agentId={currentAgent.id} />
                </CardContent>
              </Card>
            ) : activeTab === 'timeline' ? (
              /* Timeline Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-[var(--color-pastel-blue)]/20">
                      <Clock className="h-6 w-6 text-[var(--color-pastel-blue)]" />
                    </div>
                    Timeline Explorer
                  </CardTitle>
                  <CardDescription>
                    Explore {currentAgent.name}&apos;s life events and memories over time
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <TimelineExplorer events={timelineEvents} />
                </CardContent>
              </Card>
            ) : activeTab === 'relationships' ? (
              <RelationshipWorkspace
                agentId={currentAgent.id}
                agentName={currentAgent.name}
                agents={agents.map((agent) => ({ id: agent.id, name: agent.name }))}
              />
            ) : activeTab === 'learning' ? (
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-cyan-500/10">
                      <TrendingUp className="h-6 w-6 text-cyan-500" />
                    </div>
                    Meta-Learning Dashboard
                  </CardTitle>
                  <CardDescription>
                    How {currentAgent.name} adapts, discovers patterns, and sets new learning goals
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  {loadingLearning ? (
                    <div className="flex items-center justify-center py-8">
                      <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
                    </div>
                  ) : learningState ? (
                    <MetaLearningDashboard state={learningState} skills={learningSkills} />
                  ) : (
                    <div className="rounded-sm border border-dashed border-border/60 p-8 text-center text-muted-foreground">
                      Learning patterns will appear after enough conversation history is available.
                    </div>
                  )}
                </CardContent>
              </Card>
            ) : activeTab === 'scenarios' ? (
              /* Scenario Workspace V2 Tab */
              <Card className="backdrop-blur-sm border-0 bg-card/80 shadow-xl">
                <CardContent className="min-w-0 p-6">
                  <ParallelRealityExplorer
                    agentName={currentAgent.name}
                    branchPoints={scenarioBranchPoints}
                    templates={scenarioTemplates}
                    recentRuns={scenarioRuns}
                    analytics={scenarioAnalytics}
                    selectedBranchPointId={selectedBranchPoint ? `${selectedBranchPoint.kind}:${selectedBranchPoint.id}` : ''}
                    selectedIntervention={selectedIntervention}
                    activeRun={activeScenarioRun}
                    isRunning={runningScenario}
                    onSelectBranchPoint={(branchPoint) => setSelectedBranchPoint(branchPoint)}
                    onSelectTemplate={(intervention) => setSelectedIntervention(intervention)}
                    onUpdateIntervention={(intervention) => setSelectedIntervention(intervention)}
                    onOpenRun={(run) => setActiveScenarioRun(run)}
                    onRun={() => void handleRunScenario()}
                  />
                </CardContent>
              </Card>
            ) : activeTab === 'creative' ? (
              /* Creative Studio Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardContent className="p-6">
                  <CreativeStudio agentId={currentAgent.id} agentName={currentAgent.name} />
                </CardContent>
              </Card>
            ) : activeTab === 'dreams' ? (
              /* Dream Workspace V2 Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardContent className="p-6">
                  <DreamJournal agentId={currentAgent.id} agentName={currentAgent.name} />
                </CardContent>
              </Card>
            ) : activeTab === 'journal' ? (
              /* Phase 2: Journal Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardContent className="p-6">
                  <JournalViewer agentId={currentAgent.id} agentName={currentAgent.name} />
                </CardContent>
              </Card>
            ) : activeTab === 'profile' ? (
              <ProfileViewer
                agent={currentAgent as AgentRecord}
                refreshToken={profileRefreshToken}
                preferredModel={activeProviderModel}
              />
            ) : activeTab === 'challenges' ? (
              <ChallengeLab
                agentId={currentAgent.id}
                agentName={currentAgent.name}
                agents={agents as unknown as AgentRecord[]}
                activeModel={activeProviderModel}
              />
            ) : activeTab === 'knowledge-graph' ? (
              /* Phase 3: Knowledge Graph Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-emerald-500/10">
                      <Network className="h-6 w-6 text-emerald-500" />
                    </div>
                    Knowledge Graph
                  </CardTitle>
                  <CardDescription>
                    Visualize {currentAgent.name}&apos;s memory connections and concept relationships
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <KnowledgeGraph agentId={currentAgent.id} />
                </CardContent>
              </Card>
            ) : activeTab === 'knowledge-library' ? (
              /* Phase 3: Shared Knowledge Library Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-[var(--color-pastel-blue)]/20">
                      <Library className="h-6 w-6 text-[var(--color-pastel-blue)]" />
                    </div>
                    Shared Knowledge Library
                  </CardTitle>
                  <CardDescription>
                    Browse and contribute to the collective knowledge base shared by all agents
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <SharedKnowledgeLibrary
                    agentId={currentAgent.id}
                    agentName={currentAgent.name}
                    showContribute={true}
                  />
                </CardContent>
              </Card>
            ) : activeTab === 'collective' ? (
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-cyan-500/10">
                      <Users className="h-6 w-6 text-cyan-500" />
                    </div>
                    Collective Intelligence
                  </CardTitle>
                  <CardDescription>
                    Discover who knows what, validate shared knowledge, and broadcast new findings across the agent network
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <CollectiveIntelligencePanel
                    agentId={currentAgent.id}
                    agentName={currentAgent.name}
                  />
                </CardContent>
              </Card>
            ) : activeTab === 'mentorship' ? (
              /* Phase 3: Mentorship Hub Tab */
              <Card className="backdrop-blur-sm bg-card/80 border-0 shadow-xl">
                <CardHeader className="space-y-4">
                  <CardTitle className="flex items-center gap-3 text-xl">
                    <div className="p-2 rounded-sm bg-violet-500/10">
                      <GraduationCap className="h-6 w-6 text-violet-500" />
                    </div>
                    Mentorship Hub
                  </CardTitle>
                  <CardDescription>
                    Find mentors, teach others, and track {currentAgent.name}&apos;s learning journey
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <MentorshipHub
                    agentId={currentAgent.id}
                    agentName={currentAgent.name}
                    allAgents={agents as unknown as AgentRecord[]}
                  />
                </CardContent>
              </Card>
            ) : null}
          </div>
        </div>
      </main>
    </div>
  </div>
</div>
)
}
